---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Rcpp)
source("../R/convolution3d.R")
sourceCpp("../src/convolution3d.cpp")

require( rbenchmark )

G5 = array(1:24576, dim = c(512, 16, 3))     # takes about 45 seconds
H5 = array(1:2560,  dim = c(64, 8, 5))

G4 = array(1:49152, dim = c(512, 32, 3))     # takes about 2 minutes
H4 = array(1:5120,  dim = c(64, 16, 5))

G3 = array(1:393216, dim = c(512, 64, 3))     # takes about 7 minutes
H3 = array(1:40960, dim = c(64, 32, 5))

# conv3d(G5, H5)

res <- benchmark(conv3d(G5, H5), conv3d_cpp(G5, H5),
                 conv3d(G4, H4), conv3d_cpp(G4, H4),
                 conv3d(G3, H3), conv3d_cpp(G3, H3),
                 columns = c("test", "replications",
                             "elapsed", "relative"),
                 order="relative",
                 replications=2)

print(res[,1:4])

# test                    replications    elapsed     relative
# 
# 2	conv3d_cpp(G5, H5)	    2	           0.586	   1.000
# 4	conv3d_cpp(G4, H4)	    2	           2.339	   3.991
# 6	conv3d_cpp(G3, H3)	    2	           7.543	  12.872
# 1	conv3d(G5, H5)	        2	          62.779     107.131
# 3	conv3d(G4, H4)	        2	         286.787     489.398
# 5	conv3d(G3, H3)	        2	        1082.282	1846.898

```




```{r}
library(Rcpp)
library(rbenchmark)

source("../R/convolution3d.R")
sourceCpp("../src/convolution3d.cpp")

G2 = array(0, dim = c(512, 128, 3))
H2 = array(0, dim = c(64, 64, 5))

# G2 = array(1:393216, dim = c(512, 128, 3))
# H2 = array(1:40960, dim = c(64, 64, 5))

apply(G2, c(1,2), function(x) sample(c(0,1),1)) 
apply(H2, c(1,2), function(x) sample(c(0,1),1)) 

res <- benchmark(conv3d(G2, H2), conv3d_cpp(G2, H2),
                 columns = c("test", "replications",
                             "elapsed", "relative"),
                 order="relative",
                 replications=2)

print(res[,1:4])

 
# test              replications    elapsed     relative
# 2	conv3d_cpp(G2, H2)	2	        25.728	    1.000
# 1	conv3d(G2, H2)	    2	        3058.352	118.873
```


```{r}
r <- 1000
c <- 1000
m0 <- matrix(0, r, c)
apply(m0, c(1,2), function(x) sample(c(0,1),1)) 

```















